[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
bounded_vi = "5xdrKVQPYpCJ4YkzDysTmV3XPQN5vVwHV1RhAQ2xvABG"

[programs.localnet]
bounded_vi = "5xdrKVQPYpCJ4YkzDysTmV3XPQN5vVwHV1RhAQ2xvABG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet.json"

[scripts]
test = "npx --yes tsx --test tests/bounded_vi.test.ts"
