-- 016_vi_samples.sql
--
-- Raw readings behind VI sources that need their own history to measure
-- momentum: YouTube view totals sampled hourly (search discovery is
-- limited to 100 calls a day, so views are re-read from a daily set of
-- videos), and later the X and TikTok series. One row per market, source
-- and sample time; `value` is the source's own unit (views, posts,
-- hashtag post count), `meta` whatever the adapter needs to compare like
-- with like (the video set behind a YouTube total).
--
-- Written by the service role from the refresh routes; read the same
-- way. No public policy: the derived reading lives in markets.vi_components.
--
-- Idempotent.

create table if not exists public.vi_samples (
  id bigint generated by default as identity primary key,
  market_id uuid not null references public.markets(id) on delete cascade,
  source text not null,
  sampled_at timestamptz not null default now(),
  value numeric not null,
  meta jsonb
);

create index if not exists vi_samples_market_source_time_idx
  on public.vi_samples (market_id, source, sampled_at desc);

alter table public.vi_samples enable row level security;

comment on table public.vi_samples is
  'Per-source raw readings over time (YouTube views, X posts, TikTok hashtag counts) from which the adapters derive momentum';
