-- 020_vi_component_history.sql
--
-- One snapshot per market per slow (hourly) refresh of the per-source
-- breakdown behind the score. markets.vi_components is overwritten on
-- every write, so until now a calibration could only ever be fitted on
-- today's readings and a model change could not be replayed against last
-- week's. With the snapshots, scripts/vi-calibrate.ts and offline replays
-- can read any hour since this landed.
--
--   components  the breakdown as written (markets.vi_components)
--   raw_vi      the composite reading before smoothing
--   vi          the smoothed score that was written
--   attention   the total in YouTube-view-equivalents a week under the
--               calibration in force (lib/vi/score.ts CALIBRATION)
--
-- About 53 markets x 24 an hour x ~2 KB: roughly 2.5 MB a day. The slow
-- refresh deletes rows older than 60 days (lib/store.ts
-- pruneComponentHistory). Written and read by the service role; no
-- public policy.
--
-- Idempotent.

create table if not exists public.vi_component_history (
  id bigint generated by default as identity primary key,
  market_id uuid not null references public.markets(id) on delete cascade,
  recorded_at timestamptz not null default now(),
  components jsonb not null,
  raw_vi numeric,
  vi numeric,
  attention numeric
);

create index if not exists vi_component_history_market_time_idx
  on public.vi_component_history (market_id, recorded_at desc);

create index if not exists vi_component_history_time_idx
  on public.vi_component_history (recorded_at);

alter table public.vi_component_history enable row level security;

comment on table public.vi_component_history is
  'Hourly snapshots of markets.vi_components with the score written, for calibration refits and model replays. Pruned after 60 days.';
